# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DDw-JWEc3kde8ZOa4bI9wx2OsyYva_Uy
"""

import pandas
import sys

data = pandas.read_csv(sys.argv[2], delimiter=';')

print(data.head())

# Clean up column names by removing leading/trailing spaces
data.columns = data.columns.str.strip()

# Convert 'time_ms' to seconds and calculate throughput in Mbps
data['throughput_mbps'] = (data['pkt_size'] * 8) / (data['time_ms'] / 1000) / 1_000_000

# Display the updated DataFrame with the new column
display(data.head())

import matplotlib.pyplot as plt
import seaborn as sns

# Create a scatter plot
plt.figure(figsize=(7, 4)) # Increased figure size to accommodate labels on both axes
ax = sns.scatterplot(data=data, x='throughput_mbps', y='pkt_size', zorder=5) # Added zorder to ensure points are on top

# Add vertical and horizontal lines from each point to the axes
for index, row in data.iterrows():
    # Vertical line to x-axis
    ax.plot([row['throughput_mbps'], row['throughput_mbps']], [0, row['pkt_size']], color='gray', linestyle='--', linewidth=0.7, zorder=1)
    # Horizontal line to y-axis
    ax.plot([0, row['throughput_mbps']], [row['pkt_size'], row['pkt_size']], color='gray', linestyle='--', linewidth=0.7, zorder=1)


# Add labels for pkt_size on the y-axis
for index, row in data.iterrows():
    # Position the text label on the left side of the plot using the y-axis transform
    ax.text(0, row['pkt_size'], str(row['pkt_size']), fontsize=9, ha='right', va='center', transform=ax.get_yaxis_transform())

# Add labels for throughput_mbps on the x-axis
for index, row in data.iterrows():
    # Position the text label below the plot using the x-axis transform
    ax.text(row['throughput_mbps'], 0, f"{row['throughput_mbps']:.2f}", fontsize=9, ha='center', va='top', transform=ax.get_xaxis_transform())

# Set both x and y axes to a logarithmic scale
ax.set_xscale('log')
ax.set_yscale('log')


plt.title('Analise Pacotes TCP')
plt.xlabel('Largura de Banda (Mbps)')
plt.ylabel('Tamanho do Pacote (bytes)')
plt.grid(True)
plt.show()