package client.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-11-16T08:47:08.799+01:00
 * Generated source version: 4.0.3
 *
 */
@WebService(targetNamespace = "http://server/", name = "CalculadoraService")
@XmlSeeAlso({ObjectFactory.class})
public interface CalculadoraService {

    @WebMethod
    @RequestWrapper(localName = "somar", targetNamespace = "http://server/", className = "client.wsdl.Somar")
    @ResponseWrapper(localName = "somarResponse", targetNamespace = "http://server/", className = "client.wsdl.SomarResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int somar(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
