package client.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-11-16T08:47:08.858+01:00
 * Generated source version: 4.0.3
 *
 */
@WebServiceClient(name = "CalculadoraServiceService",
                  wsdlLocation = "http://localhost:8080/calculadora?wsdl",
                  targetNamespace = "http://server/")
public class CalculadoraServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server/", "CalculadoraServiceService");
    public final static QName CalculadoraServicePort = new QName("http://server/", "CalculadoraServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/calculadora?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CalculadoraServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/calculadora?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CalculadoraServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CalculadoraServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculadoraServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CalculadoraServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CalculadoraServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CalculadoraServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CalculadoraService
     */
    @WebEndpoint(name = "CalculadoraServicePort")
    public CalculadoraService getCalculadoraServicePort() {
        return super.getPort(CalculadoraServicePort, CalculadoraService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculadoraService
     */
    @WebEndpoint(name = "CalculadoraServicePort")
    public CalculadoraService getCalculadoraServicePort(WebServiceFeature... features) {
        return super.getPort(CalculadoraServicePort, CalculadoraService.class, features);
    }

}
